application: papersetal
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: static/img/favicon\.ico

- url: /apple-touch-icon\.png
  static_files: apple-touch-icon.png
  upload: static/img/apple-touch-icon\.png

- url: /static
  static_dir: static/

- url: /static/css
  mime_type: text/css
  static_dir: static/css

- url: /static/js
  mime_type: text/javascript
  static_dir: static/js

- url: /static/img
  static_dir: static/img

- url: /static/img/favicons
  static_dir: static/img/favicons

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  script: main.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
